### PR TITLE
Buildfix.

### PR DESCRIPTION
**Pull request by UltraNix**
Test with https://github.com/azerothcore/azerothcore-wotlk/pull/9729

### CODE REVIEW

**Comment by temperrr** [comment]
CONFLICT (modify/delete): cmake/after_load_cmake_modules.cmake deleted in HEAD and modified in be50e3d85ed9780c67d3a5144f8e23a09a1abab5. Version be50e3d85ed9780c67d3a5144f8e23a09a1abab5 of cmake/after_load_cmake_modules.cmake left in tree.
Automatic merge failed; fix conflicts and then commit the result.

**Comment by UltraNix** [comment]
@temperrr Got no problem with it :(

**Comment by temperrr** [comment]
MAybe I am just stupid then...

**Comment by temperrr** [comment]
Ok how do I test this PR, I think I do it wrong. How can I load this into my eluna?

**Comment by 55Honey** [comment]
I just clone it somewhere else manually and copy it over  :)

**Comment by UltraNix** [comment]
Yep - you can just copy it manually to your Eluna.

**Comment by temperrr** [comment]
Ok I give this a try tomorrow

**Comment by temperrr** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C3861	'TaxiPathBySourceAndDestination': identifier not found (compiling source file H:\Azerothcore\modules\mod-eluna-lua-engine\src\LuaEngine\LuaFunctions.cpp)	modules	H:\Azerothcore\modules\mod-eluna-lua-engine\src\LuaEngine\GlobalMethods.h	2422	
Error	LNK2019	unresolved external symbol "private: bool __cdecl ReputationMgr::SetReputation(struct FactionEntry const *,int,bool,bool,bool)" (?SetReputation@ReputationMgr@@AEAA_NPEBUFactionEntry@@H_N11@Z) referenced in function "int __cdecl LuaPlayer::SetReputation(struct lua_State *,class Player *)" (?SetReputation@LuaPlayer@@YAHPEAUlua_State@@PEAVPlayer@@@Z)	worldserver	F:\Build\src\server\worldserver\modules.lib(LuaFunctions.obj)	1	
Error	LNK2001	unresolved external symbol "class std::map<unsigned int,class std::map<unsigned int,struct TaxiPathBySourceAndDestination,struct std::less<unsigned int>,class std::allocator<struct std::pair<unsigned int const ,struct TaxiPathBySourceAndDestination> > >,struct std::less<unsigned int>,class std::allocator<struct std::pair<unsigned int const ,class std::map<unsigned int,struct TaxiPathBySourceAndDestination,struct std::less<unsigned int>,class std::allocator<struct std::pair<unsigned int const ,struct TaxiPathBySourceAndDestination> > > > > > sTaxiPathSetBySource" (?sTaxiPathSetBySource@@3V?$map@IV?$map@IUTaxiPathBySourceAndDestination@@U?$less@I@std@@V?$allocator@U?$pair@$$CBIUTaxiPathBySourceAndDestination@@@std@@@3@@std@@U?$less@I@2@V?$allocator@U?$pair@$$CBIV?$map@IUTaxiPathBySourceAndDestination@@U?$less@I@std@@V?$allocator@U?$pair@$$CBIUTaxiPathBySourceAndDestination@@@std@@@3@@std@@@std@@@2@@std@@A)	worldserver	F:\Build\src\server\worldserver\modules.lib(LuaFunctions.obj)	1	
Error	LNK1120	2 unresolved externals	worldserver	F:\Build\bin\RelWithDebInfo\worldserver.exe	1

**Comment by UltraNix** [comment]
@temperrr Try this one instead that PR: https://github.com/UltraNix/Eluna/commit/08808d90c335335f3c9aa9985182dc622e228acc

**Comment by UltraNix** [comment]
@temperrr ??

**Comment by temperrr** [comment]
Testing

**Comment by temperrr** [comment]
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	C3861	'TaxiPathBySourceAndDestination': identifier not found (compiling source file H:\Azerothcore\modules\mod-eluna-lua-engine\src\LuaEngine\LuaFunctions.cpp)	modules	H:\Azerothcore\modules\mod-eluna-lua-engine\src\LuaEngine\GlobalMethods.h	2422	
>

**Comment by UltraNix** [comment]
@temperrr And you applied my fix from https://github.com/UltraNix/Eluna/commit/08808d90c335335f3c9aa9985182dc622e228acc?

**Comment by temperrr** [comment]
azerothcore/azerothcore-wotlk#9729
UltraNix@08808d9

these two, yes

**Comment by temperrr** [comment]
Unless I did it completely wrong?

**Comment by 55Honey** [comment]
I kept failing to apply PRs to Eluna. The only way for me to make it work, was to manually apply the changes.

**Comment by temperrr** [comment]
Yea I manually added the lines

**Comment by UltraNix** [comment]
Only this one https://github.com/UltraNix/Eluna/commit/08808d90c335335f3c9aa9985182dc622e228acc
And yes -add files manually.

**Comment by temperrr** [comment]
If it compiles for you then I am ok, cause I then probably do something wrong

**Comment by UltraNix** [comment]
I did not test it.
Try to pull "fresh" sources and then only apply this last commit.

**Comment by temperrr** [comment]
But I need to test with the original pr no?
azerothcore/azerothcore-wotlk#9729

**Comment by UltraNix** [comment]
Yes.

**Comment by temperrr** [comment]
Ok it build
can u PR this and merge it, then mark the other one as to be merged?

**Comment by UltraNix** [comment]
Same problem as @55Honey  - I don't know how to make a PR of it. :(

**Comment by UltraNix** [comment]
Superseded by https://github.com/UltraNix/Eluna/commit/08808d90c335335f3c9aa9985182dc622e228acc

**Pull request closed without merging**
